# Generated by Django 3.2.4 on 2021-06-22 04:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=12)),
            ],
        ),
    ]
